balloonCat = {
  src: "./animationSrc/balloonCatSpritesheet.png",
  img: undefined,
  frame: 0,
  offset: 0,
  frames: [
    {
      filename: "tile000.png",
      frame: {
        x: 1,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile001.png",
      frame: {
        x: 483,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile002.png",
      frame: {
        x: 965,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile003.png",
      frame: {
        x: 1447,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile004.png",
      frame: {
        x: 1929,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile005.png",
      frame: {
        x: 2411,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile006.png",
      frame: {
        x: 2893,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile007.png",
      frame: {
        x: 1,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile008.png",
      frame: {
        x: 483,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile009.png",
      frame: {
        x: 965,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile010.png",
      frame: {
        x: 1447,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile011.png",
      frame: {
        x: 1929,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile012.png",
      frame: {
        x: 2411,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile013.png",
      frame: {
        x: 2893,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile014.png",
      frame: {
        x: 1,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile015.png",
      frame: {
        x: 483,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile016.png",
      frame: {
        x: 965,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile017.png",
      frame: {
        x: 1447,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile018.png",
      frame: {
        x: 1929,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile019.png",
      frame: {
        x: 2411,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile020.png",
      frame: {
        x: 2893,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile021.png",
      frame: {
        x: 1,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile022.png",
      frame: {
        x: 483,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile023.png",
      frame: {
        x: 965,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile024.png",
      frame: {
        x: 1447,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile025.png",
      frame: {
        x: 1929,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile026.png",
      frame: {
        x: 2411,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile027.png",
      frame: {
        x: 2893,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile028.png",
      frame: {
        x: 1,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile029.png",
      frame: {
        x: 483,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile030.png",
      frame: {
        x: 965,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile031.png",
      frame: {
        x: 1447,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile032.png",
      frame: {
        x: 1929,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile033.png",
      frame: {
        x: 2411,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile034.png",
      frame: {
        x: 2893,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile035.png",
      frame: {
        x: 1,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile036.png",
      frame: {
        x: 483,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile037.png",
      frame: {
        x: 965,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile038.png",
      frame: {
        x: 1447,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile039.png",
      frame: {
        x: 1929,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile040.png",
      frame: {
        x: 2411,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile041.png",
      frame: {
        x: 2893,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile042.png",
      frame: {
        x: 1,
        y: 2893,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile043.png",
      frame: {
        x: 483,
        y: 2893,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile044.png",
      frame: {
        x: 965,
        y: 2893,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile045.png",
      frame: {
        x: 1447,
        y: 2893,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile046.png",
      frame: {
        x: 1929,
        y: 2893,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile047.png",
      frame: {
        x: 2411,
        y: 2893,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile048.png",
      frame: {
        x: 2893,
        y: 2893,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile049.png",
      frame: {
        x: 3375,
        y: 1,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile050.png",
      frame: {
        x: 3375,
        y: 483,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile051.png",
      frame: {
        x: 3375,
        y: 965,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile052.png",
      frame: {
        x: 3375,
        y: 1447,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile053.png",
      frame: {
        x: 3375,
        y: 1929,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
    {
      filename: "tile054.png",
      frame: {
        x: 3375,
        y: 2411,
        w: 480,
        h: 480,
      },
      rotated: false,
      trimmed: false,
      spriteSourceSize: {
        x: 0,
        y: 0,
        w: 480,
        h: 480,
      },
      sourceSize: {
        w: 480,
        h: 480,
      },
    },
  ],
  meta: {
    app: "http://www.codeandweb.com/texturepacker",
    version: "1.0",
    image: "spritesheet.png",
    format: "RGBA8888",
    size: {
      w: 3856,
      h: 3374,
    },
    scale: "1",
  },
};
